### ISSUE TITLE
Tracking futurewarnings and deprecations in lectures

### ISSUE THREAD

**Issue by doctor-phil** [QuantEcon/lecture-datascience.myst#262]
- [x] `pandas/timeseries.md` 
  - FutureWarning: 'BQ' is deprecated and will be removed in a future version, please use 'BQE' instead. `btc_usd.resample("BQ").mean()`
- [x] `pandas/data_clean.md`: 
  - FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead. `df.fillna(method="bfill")`
  - FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead. `df.fillna(method="ffill")`
- [x] `pandas/reshape.md`:
  - FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning. `bball_wide.stack()`
  - same warning appears in 5 areas. New version of `stack`/`unstack` is the same, but creates fewer NaN. Shouldn't really need to fix but good to track
- [x] `pandas/groupby.md`:
   - DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning. `gbA.apply(smallest_by_b)`
   - FutureWarning: 'BQ' is deprecated and will be removed in a future version, please use 'BQE' instead. `df2["Date"] = pd.date_range(...`
   - FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead. `df2.groupby(pd.Grouper(key="Date", freq="A")).count()`
   - FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning. `reshaped = aggs.stack().T.swaplevel(axis=1).sort_index(axis=1)`

**Comment by doctor-phil** [comment]
- [ ] `tools/matplotlib.md`:
  - DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning. `to_plot = prices.groupby("Model").apply(scale_by_middle).T`

**Comment by doctor-phil** [comment]
- [ ] `applications/networks.md`:
  - FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead. `adj = corr.applymap(truncate) - np.identity(10)`
- [ ] `applications/recidivism.md`:
  - FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning. `counts = df.groupby(group_col)["name"].count().sort_index()`

**Comment by doctor-phil** [comment]
I am not fixing deprecated stack, since it seems like it will update automatically. If I add the `future_stack=True` argument, it's just going to cause more issues down the road when that argument gets deprecated...
